typography_spectrum: 0.22042168490588665
color:
  brandStrength: 0.05278467736206949
  lightness: 0.6867812427226454
  saturation: 0.433956294786185
  rhythmicContrast: 0.21191638708114624
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.009610348613932729
name: CannaCulture
navigation:
  - name: 'Kalanchoe '
    url: 'http://jlplants.com/jlplants.com/Home.html'
    type: external
title: J&L Plants Inc.
description: Horticulture Specialist
